using System.Reflection.Metadata;

namespace assignmentoop02
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Part 01 — Theoretical Questions
            //Q1 Object Copying

            //a) What happens when you assign one object variable to another object variable?
            //b) Does assigning one object to another create a new object? Explain.
            //c) What is the difference between copying an object and copying its reference?

            //الاتنين بيبقي ليهم نفس العنوان فبيشاورو علي نفس الاوبجكت واي تعديل فاي واحد منهم يسمع في التاني 
            // لا طالما بساوي اتنين اوبجكت فانا هساوي العنوان وليس انشئ اوبجكت جديد
            // اني اعمل كوبي لاوبجكت فده معناه انه يدييني صلاحيه اني اتجكم فيه وكل واحد يبقي مستقل ليه الاوبجكت بتاعه  اما نسخ العنوان فالاتنين بيشاورو علي نفس الاوبجكت ونفس البيانات واي تعديل هيسمع عند التانيي عشان هو عنوان وليس نسخ لقلقيم الي جوا

            // Q2 Shallow Copy vs Deep Copy
            //a) What is a Shallow Copy?
            //b) What is a Deep Copy?
            //c) What happens to reference-type members when a Shallow Copy is created?
            //d) What happens to reference-type members when a Deep Copy is created?
            //e) Give one situation where Deep Copy would be safer than Shallow Copy.

            //هو نسخ المستوي الاول من الاوبجكت فقط 
            // هو نسخ الاوبجكت بجميع المتغيرات الي فيه حتي لو كان في اوبجكت جوا اوبجكت فانا بوصل لاقصي نوع من النسخ وبيبقي مستقل بشكل كلي
            // علي حسب لو سترينج فهو غير قابل للتعديل فعشان كده بيتم معاملته كاني عملت فعلا نسخ ليه وبيبقي مستقل اما لو ريفرينس تايب تاني فسعتها باخد نسخه منه ومش بنشا منه اوبجكت مستقل
            // بيكون مستقل بشكل كامل وكل اوبجكت اقدر اتحكم فيه لوحده 
            // لو عندي داخل الاوبجكت الاولاني كلاس فسعتها لازم يتعمله ديب كوبي عشان المتغير الي من نوع كلاس يتعمله اوبجكت جديد هو كمان ويبقي مستقل

            //Q3 Static Members
            //a) What is a static field, and how is it different from an instance field ?
            //b) What is a static method? Can a static method directly access instance members?
            //c) What is a static constructor, and when is it executed ?
            //d) What is a static class? Can you create an object from a static class?

            // الفرق ان المتغير الستاتيك بقدر اناديه من اسم الكلاس بالاضافه انه بيبقي ثابت مش بيتغير بعد كل اوبجكت جديد بعمله  
            // هي ميثود بقدر اناديها من الكلاس بشكل مباشر بدون الحاجه اني اعمل منها اوبجكت ولازم يكون المتغيرات الي جواها ستاتيك 
            //  هو عباره عن حاجه بتتنفذ اول ما الكلاس بيتنادي عليه او بيتم استخدامه بقدر احفظ فيها حاجات ستاتيك واديها قيمه عشان اول ما يتم بناء اول اوبجكت يخش ينفذه او الاشاره ليه باي طريقه
            // مش بقدر انشي منه اوبجكت هو بيبقي بداخله قيم ستاتيك بستخدمه عن طريق اسمه ممكن استفاد منه بحاجه بتكون مساعده بستخدمها في مشاريعي ومش بحتاج انشي منها اوبجكت زي math in c#

            //Q4 Extension Methods
            //a) What is an Extension Method?
            //b) What keyword must be used in the first parameter of an extension method?
            //c) Where must an extension method be declared?
            //d) Can an extension method access private members of the class it extends?
            // هي ميثود بضيفها عن طريق كلاس تاني ستاتيك وبتكون ستاتيتك بتاخد القيه من الي بينادي عليها 
            // this nameclass 
            // static class
            // no becouse you can used and acces


//  Q5 Partial Classes and Partial Methods
//a) What is a Partial Class?
//b) Why would a developer split one class into multiple files?
//c) What is a Partial Method?
//d) What happens if a declared partial method has no implementation?
            
            //هو كلاس بيتم تقسيمه 
            //عشان قدام هيتم استخدامه اكتر عن طريق واحد منهم يبقي فيه auto generated by tools  ودي بتم تلقائي من الداتا بيز الي عندي والتاني بيتم فيه لوجيك والبيزنس بتاعي
            // هي عباره عن ميثود يتم تقسيمها جزء فيه signture and the other partial class implment 
            // بيتم تجاهل بس لازم اني اكتب الميثود واعمل قوس امبلمينت بس لو مكتبتش حاجه جوا فعادي ولازم طبعا تكون الداله مش بترجع قيمه لانها لو بترجع قيمه هيدي ايرور اصلا ولازم امبلمينت
            #endregion
        #region Part 02 — Practical

            Shipment sh01 = new StandardShipment("sh001", "laptop", 10m, 15m, new DeliveryAddress("cairo", "altahrir", 5));
            Shipment sh02 = sh01;
            Console.WriteLine(sh01.Description);
            Console.WriteLine(sh02.Description);
            sh01.Description = "aaaaaaaa";
            Console.WriteLine(sh01.Description);
            Console.WriteLine(sh02.Description);
            // have the two are changed bacouse that refernce have the same object
            Shipment sh03shallow = sh01.shallowcopy();
            Console.WriteLine(sh03shallow.Destination.City);
            Console.WriteLine(sh01.Destination.City);
            sh03shallow.Destination.City = "giza";
            Console.WriteLine(sh03shallow.Destination.City);
            Console.WriteLine(sh01.Destination.City);
            // shallow copying copy the first level only
            Shipment sh02exp = new ExpressShipment("sh000","mobile",10m,80m,new DeliveryAddress("tanta","ssss",5), 55m);
            Shipment sh03int = new InternationalShipment("sh000","mobile",10m,80m,new DeliveryAddress("tanta","ssss",5), "ffff",55m);



            //Create a Deep Copy.
            Shipment sh04deep = sh01.DeepCopy();
            Console.WriteLine(sh04deep.Destination.Street);
            Console.WriteLine(sh01.Destination.Street);
            sh01.Destination.Street = "albhoth";
            Console.WriteLine(sh04deep.Destination.Street);
            Console.WriteLine(sh01.Destination.Street);
            Console.WriteLine($"TotalShipmentsCreated : {Shipment.TotalShipmentsCreated}");
            DeliveryUtilities.PrintSystemTitle();
            DeliveryUtilities.PrintSeparator();
            Console.WriteLine("-------------------------------------------------------------------------\n");

            Console.WriteLine(ShipmentExtensions.GetSummary(sh01));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            Console.WriteLine(ShipmentExtensions.GetSummary(sh02exp));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            Console.WriteLine(ShipmentExtensions.GetSummary(sh03int));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            Console.WriteLine(ShipmentExtensions.IsDelivered(sh01));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            Console.WriteLine(ShipmentExtensions.IsDelivered(sh02exp));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            Console.WriteLine(ShipmentExtensions.IsDelivered(sh03int));
            Console.WriteLine("-------------------------------------------------------------------------\n");
            sh01.OnTrackingStatusChanged("pppppppp");
            #endregion
            
        }


    }
}
